spring: 
  mvc: 
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        implicit_naming_strategy: com.cetian.base.configuration.db.ZeusImplicitNamingStrategyImpl
        hbm2ddl:
          auto:
  datasource:
    db1: 
      type: org.apache.tomcat.jdbc.pool.DataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/admin1?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true
      username: root
      password: root
  cache:
    redis1:
      hostname: localhost
      port: 6379
      password:
      clientName: ct
      readTimeout: 5
      connectTimeout: 5
      
